### ISSUE TITLE
Adding support for PICO W

### ISSUE THREAD

**Issue by jtoland** [erdemarslan/hid-keyboard-micropython#1]
Hello,

I have just tried this and love what you have done here as there are not many examples on how to do this for micropython.

I was wondering if you could build a new firmware so that it works for the pico w as this would really be useful.

Kind Regards,
Jason

**Comment by erdemarslan** [comment]
Hi,
I didn't generate firmware file. You can read original post from Raspberry Pi forums:
Original Post: (noobeepi) https://forums.raspberrypi.com/viewtopic.php?t=310876&start=50

Pico W hasn't stable micropython firmware yet. Maybe micropython developer team will be add hid support to Pico and W.
